---
title: "Foundation lab 4 Code-along"
author: "Jeanne McClure"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 1. Prepare
```{r}
#load libraries
library(tidyverse)
library(here)


```

## 2. Wrangle
Read in survey data from the previous session
```{r}
survey <- read_csv(here("data", "survey.csv"))

# Choose a way to inspect your datat with what ever function you wish
```


## Explore



#### A. TABLE SUMMARY
```{r}
#install package if this is first time using skimr


#load library
library(skimr)

#skim data
skim(data_to_explore)

```

## B. TIDY to EXPLORE
```{r}
# using the `select()` and `filter()` functions. In the code chunk below,look at descriptive for just `proportion_earned` , `time_spent` and `gender`, but only for the "OcnA" and "PhysA" subjects.

data_to_explore %>% 
  select(c('subject', 'gender', 'proportion_earned', 'time_spent')) %>% 
  filter(subject == "OcnA" | subject == "PhysA") %>%
  skim()
```


#### B. DATA VIZ

ggplot grammar - with layers


##### layers - Scatter Plot

Basic graph 
1. data
2. aes
3. geom

```{r}
#layer 1: add data and aesthetics mapping 
ggplot(data_to_explore, #<<
       aes(x = time_spent_hours, 
           y = proportion_earned)) +
#layer 2: +  geom function type
  geom_point() #<<
```

Add **Scale ** with different color for enrollment status.

```{r}
#layer 1: add data and aesthetics mapping 
#layer 3: add color scale by type
ggplot(data_to_explore, 
       aes(x = time_spent_hours, 
           y = proportion_earned,
           color = enrollment_status)) + #<<
#layer 2: +  geom function type
  geom_point()
```


Add another layer with **labs* labeling the title
```{r}
#layer 1: add data and aesthetics mapping 
#layer 3: add color scale by type
ggplot(data_to_explore, 
       aes(x = time_spent_hours, 
           y = proportion_earned,
           color = enrollment_status)) +
#layer 2: +  geom function type
  geom_point() +
#layer 4: add lables
  x_lab(title="How Time Spent on Course LMS is Related to Points Earned in the Course", x="Time Spent (Hours)", y = "MProportion of Points Earned")
```


Add the **facet** layer
```{r echo = TRUE, eval=FALSE}
#layer 1: add data and aesthetics mapping 
#layer 3: add color scale by type
ggplot(data_to_explore, aes(x = time_spent_hours, y = proportion_earned, color = enrollment_status)) +
#layer 2: +  geom function type
  geom_point() +
#layer 4: add lables
    x_lab(title="How Time Spent on Course LMS is Related to Points Earned in the Course", 
       x="Time Spent (Hours)",
       y = "Proportion of Points Earned")
#layer 5: add facet wrap
  facet_wrap(~ subject) 
```




##### layers- Histogram
```{r}
# create a histogram
data_to_explore %>% 
  ggplot(aes(x = time_spent_hours)) +
  geom_histogram(bins = 30)

```

